sudo: required

services:
  - docker
  
language: cpp

compiler:
- gcc

env:
- CMAKE_BUILD_TYPE=Debug

before_script:
  - docker build --tag image --build-arg CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -f Dockerfile.dev .
  - CONTAINER=$(docker create image)
  - docker cp $CONTAINER:/kui/docs docs

script:
  - docker run image ./kui_test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: stable