sudo: required

services:
  - docker
  
language: cpp

env:
- CMAKE_BUILD_TYPE=Debug
- CMAKE_BUILD_TYPE=Release

before_script:
  - docker build --tag myImage --build-arg CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} .

script:
  - docker run myImage ./kui_test
