sudo: required

services:
  - docker

env:
  - CMAKE_BUILD_TYPE=Debug CC=gcc CXX=g++
  - CMAKE_BUILD_TYPE=Debug CC=clang CXX=clang++
  - CMAKE_BUILD_TYPE=Release CC=gcc CXX=g++
  - CMAKE_BUILD_TYPE=Release CC=clang CXX=clang++

before_script:
  - docker build --tag development --build-arg CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} --build-arg CC=${CC} --build-arg CXX=${CXX} -f Dockerfile.dev .

script:
  - docker run --rm development build/kui_test
  
before_deploy:
  - docker run --rm -v ${TRAVIS_BUILD_DIR}/docs:/prj/docs development doxygen
  - sudo chown -R ${USER}:${USER} docs/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: stable
    condition: $CMAKE_BUILD_TYPE = Debug
    condition: $CC = gcc