sudo: required

services:
  - docker
  
language: cpp

compiler:
- gcc

env:
- CMAKE_BUILD_TYPE=Debug
- CMAKE_BUILD_TYPE=Release

before_script:
  - docker build --tag development --build-arg CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -f Dockerfile.dev .

script:
  - docker run --rm development build/kui_test
  
before_deploy:
  - docker run --rm -v ${TRAVIS_BUILD_DIR}/docs:/prj/docs development doxygen
  - sudo chown -R ${USER}:${USER} docs/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: stable
    condition: "$CMAKE_BUILD_TYPE=Debug"