FROM alpine:latest

ARG CMAKE_BUILD_TYPE=Release
ARG CC=gcc
ARG CXX=g++

RUN apk add --no-cache gcc g++ clang make cmake gtest gtest-dev doxygen
ADD . prj
WORKDIR prj

RUN mkdir build
WORKDIR build

RUN cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
RUN make

WORKDIR ..

CMD ["echo", "Nothing to run."]
