FROM alpine:latest

ARG CMAKE_BUILD_TYPE=Debug

RUN apk add --no-cache gcc g++ clang make cmake gtest gtest-dev doxygen
ADD . prj
WORKDIR prj

RUN doxygen

RUN mkdir build
WORKDIR build

RUN cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
RUN make

WORKDIR ..

CMD ["build/kui_test"]
